### ISSUE TITLE
jd_bean_sign.js error

### ISSUE THREAD

**Issue by sxdxzkq** [inoyna12/JDsc#10]
❗️京东多合一签到, 错误!
SyntaxError: Unexpected token r in JSON at position 0
    at JSON.parse (<anonymous>)
    at /ql/scripts/inoyna12_JDsc/jd_bean_sign.js:75:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by inoyna12** [comment]
同步仓库再试一下

**Comment by sxdxzkq** [comment]
> 同步仓库再试一下

成功了
