### ISSUE TITLE
安装依赖失败

### ISSUE THREAD

**Issue by sxdxzkq** [inoyna12/JDsc#3]
开始安装依赖 jsdom，开始时间 2022/5/29 00:46:59

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.

依赖安装失败，结束时间 2022/5/29 00:47:00，耗时 1.046 秒

全部JS的依赖都无法安装，这是什么原因？

**Comment by inoyna12** [comment]
青龙版本问题

**Comment by sxdxzkq** [comment]
我退回到12了
