### ISSUE TITLE
执行出错

### ISSUE THREAD

**Issue by ABC15768** [inoyna12/JDsc#5]
日志显示执行出错！手机挂了一天，一个任务也没自动完成，ck在青龙里运行是有效的

**Comment by inoyna12** [comment]
> 日志显示执行出错！手机挂了一天，一个任务也没自动完成，ck在青龙里运行是有效的

可能是依赖没装好，现在正在测试手机安装青龙，能运行的话我会在库里发教程

**Comment by ABC15768** [comment]
好的，期待作者能弄好青龙！
