### ISSUE TITLE
青龙面板

### ISSUE THREAD

**Issue by ABC15768** [inoyna12/JDsc#7]
大佬，为什么我弄好了面具，刷入模块没法选中，怎么办

**Comment by ABC15768** [comment]
现在刷入了面板，但是busybox不会用，无法安装在/system/xbin目录下，提示储存空间不足，安装在其他位置可行

**Comment by ABC15768** [comment]
安装不了xbin位置，SSH连接不上

**Comment by ABC15768** [comment]
> > 现在刷入了面板，但是busybox不会用，无法安装在/system/xbin目录下，提示储存空间不足，安装在其他位置可行
> 
> 可能是手机的原因，去酷安找busybox模块试试

安装了busybox模块，SSH还是连不上

**Comment by inoyna12** [comment]
> > > 现在刷入了面板，但是busybox不会用，无法安装在/system/xbin目录下，提示储存空间不足，安装在其他位置可行
> > 
> > 
> > 可能是手机的原因，去酷安找busybox模块试试
> 
> 安装了busybox模块，SSH还是连不上

你连接ssh要安装什么？
