### ISSUE TITLE
能否增加一个推送渠道？

### ISSUE THREAD

**Issue by Flying-Cabbage** [inoyna12/JDsc#8]
您好，请问能增加gocqhttp推送吗，这是他的网址https://docs.go-cqhttp.org/

**Comment by inoyna12** [comment]
> 您好，请问能增加gocqhttp推送吗，这是他的网址https://docs.go-cqhttp.org/

sendNotify.js里面有

**Comment by Flying-Cabbage** [comment]
![图片](https://user-images.githubusercontent.com/54514945/143859043-61822b49-90de-4410-971f-d7ca7102de49.png)
我配置了gobot需要的参数，但是没有推送，应该是脚本里面没有调用这个推送gobot的方法，您可以看一下吗

**Comment by inoyna12** [comment]
重新变动了一下sendNotify.js(照抄别人的)，看了一下有2种，go-cqhttp和原生go-cqhttp通知，也都调用了。
我没用过这个通知，你自行添加所需的变量测试下，不行的话在回复我

**Comment by Flying-Cabbage** [comment]
![图片](https://user-images.githubusercontent.com/54514945/143871751-5ec4f012-8ce7-4597-8b25-92232f37ef3d.png)
![图片](https://user-images.githubusercontent.com/54514945/143871865-e55db40f-196f-4ecb-9164-a45523166d22.png)
还是不行

**Comment by Flying-Cabbage** [comment]
![图片](https://user-images.githubusercontent.com/54514945/143872845-da564d82-ed85-4de6-9fde-3a591a2967a7.png)
格式用该是这样，这是个普通post请求，不需要json形式参数

**Comment by inoyna12** [comment]
你试试青龙作者的推送脚本
https://github.com/whyour/qinglong/blob/develop/sample/notify.js
